### ISSUE TITLE
Left handed coordinate system on banner.png?

### ISSUE THREAD

**Issue by nicolas-heigvd** [opengeospatial/GeoPoseSandbox#4]
A tiny detail but it seems that the drawn frame on the left on this .png file doesn't have the same handedness as the two others, is that on purpose?

https://github.com/opengeospatial/GeoPoseSandbox/blob/development/docs/banner.png

**Comment by MikelSalazar** [comment]
I was not intending for the torus around the axis to represent the handedness of the coordinate system (because it was more about rotation than location), but I'll check if this can cause a problem. 

Just to clarify, I was original inspired by this [image](https://en.wikipedia.org/wiki/Aircraft_principal_axes#/media/File:Flight_dynamics_with_text_ortho.svg), but I placed the toruses (tori?) around the axes without paying attention to their position.
